
version: '3.8'

services:
  llama-gpu:
    image: wiiit/llama-gpu:pytorch.v23.04-py3
    working_dir: /app
    volumes:
      - ..:/app
    network_mode: host
    stdin_open: true
    tty: true
    deploy:
          resources:
            reservations:
              devices:
                - driver: nvidia
                  count: ${NGPUS}
                  capabilities: [gpu]
    shm_size: '320gb'
    command: /bin/bash -c "pip install -e . && /bin/bash"
