version: '3.0'

services:
  llama-dev:
    image: python:3.10.12
    working_dir: /app
    volumes:
      - ..:/app
    environment:
      - RANK=0
      - WORLD_SIZE=4
      - MASTER_ADDR=10.1.133.12
      - MASTER_PORT=12345
    network_mode: host
    stdin_open: true
    tty: true
    command: ["/bin/bash"]
