version: '3.0'

services:
  llama-dev:
    image: wiiit/llama-cpu:python_3.10.12-pytorch_2.1.0
    working_dir: /app
    volumes:
      - ..:/app
    network_mode: host
    stdin_open: true
    tty: true
    command: /bin/bash -c "pip install -e . && /bin/bash"
