
services:
  llama-dev:
    image: nvcr.io/nvidia/pytorch:22.04-py3
    working_dir: /app
    volumes:
      - ..:/app
    environment:
      - RANK=0
      - WORLD_SIZE=1
      - MASTER_ADDR=localhost
      - MASTER_PORT=12345
    network_mode: host
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: ["/bin/bash"]
